import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const styles = {
  footer: {
    backgroundColor: "#a2a2a2",
    color: "white",
    padding: "20px 0",
    textAlign: "center",
    marginTop: "auto",
  },
  container: {
    maxWidth: "800px",
    margin: "0 auto",
    padding: "0 15px",
  },
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}
      >
        <header className="flex justify-between items-center text-white p-4">
          <div className="text-xl font-bold">
            <a href="/">TrackMyMoney</a>
          </div>
          <nav className="flex gap-4">
            <a href="/" className="hover:underline">
              Home
            </a>
            <a href="/dashboard" className="hover:underline">
              Dashboard
            </a>
            <a href="/transactions" className="hover:underline">
              Transações
            </a>
            <a href="/account" className="hover:underline">
              Conta
            </a>
          </nav>
        </header>
        {children}

        <footer style={styles.footer}>
          <div style={styles.container}>
            <p>Feito por Matias</p>
            <p className=" hover:text-black transition duration-300">
              <a
                href="https://github.com/Matiaszz"
                target="_blank"
                rel="noopener noreferrer"
              >
                GitHub
              </a>
            </p>
            <p className=" hover:text-black transition duration-300">
              <a href="mailto:allangiovannimatias@hotmail.com">
                allangiovannimatias@hotmail.com
              </a>
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
